### ISSUE TITLE
Filtered balancers do not output if one of the exits has backpressure

### ISSUE THREAD

**Issue by timspeedle** [factropy/community#15]
If you build a set of balancers with filters on different balancers to sort the inputs, incoming items will not be put onto an exit if there is "backpressure" on one of the output lines.

For example, if a balancer is outputting both Steel and Copper ingots, and the Copper ingots line is backed up such that the balancer is not outputting anything to that line, then Steel ingots will not be pushed through to the exit belt until at least some copper ingots are first pulled out of the balancer array.

**Comment by d0rfl** [comment]
The immediate bug is fixed in 0.1.27, but the balancer component has a complex state machine covering:

- N balancers in a group
- Priority input
- Priority output
- Filtered output
- Load balancing

Please watch for other strange emergent behaviour. The default load balancing component uses a round-robin process based on game tick, but it seems likely that different combinations of N, priority and filter could cause unexpected edge cases.
